////////////////////////////////////////////////////////////////////////////////
//
// dummyshipdata.js
//
// Measurement of Net Community Production (MoNCP) of the World's Oceans:
//
// A web application that supports the viewing and analysis of data generated by
// the Nicolas Cassar Laboratory of Duke University's Nicholas School of the
// Environment.  From http://www.nicholas.duke.edu/people/faculty/cassar/: "Our
// research focuses on environmental biogeochemistry and physiology, with the
// objective of constraining the mechanisms governing carbon cycling and
// climate."
//
//
// Web application author:
//
// Steve Chall, Renaissance Computing Institute: stevec@renci.org
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//
// Return a random value r such that min <= r <= max.
//
////////////////////////////////////////////////////////////////////////////////
var rVal = function(min, max) {
  return (min +  Math.random() * (max - min)).toFixed(4);
}

////////////////////////////////////////////////////////////////////////////////
//
// Right now, just arbitrarily creating six Ship objects plus an array of three
// of each variable for numObjects ShipDataSetObjects.
//
////////////////////////////////////////////////////////////////////////////////
var generateDummyShipData = function(numObjects) {
  new Ship("ship0", "a0", ["b0", "c0"], 0);
  new Ship("ship1", "a1", ["b1"], 1);
  new Ship("ship2", "a2", ["b2", "c2", "d2"], 2);
  new Ship("ship3", "a3",["b3"], 3);
  new Ship("ship4", "a4",["b4"], 4);
  new Ship("ship5", "a5",["b5", "c5"], 5);

  for (var i = 0; i < numObjects; i++) {
    var year = new Date();
    year.setFullYear(Math.floor(rVal(1997, 2012)));
    var ship = Ship.all[Math.floor(rVal(0, Ship.all.length - 1))];
    ShipDataSet.all.push(new ShipDataSet(
    /* o2ar */  rVal(ShipDataSet.O2AR_MIN, ShipDataSet.O2AR_MAX),
    /* ncp */   rVal(ShipDataSet.NCP_MIN, ShipDataSet.NCP_MAX),
    /* sal */   rVal(ShipDataSet.SAL_MIN, ShipDataSet.SAL_MAX),
    /* temp */  rVal(ShipDataSet.TEMP_MIN, ShipDataSet.TEMP_MAX),
    /* press */ rVal(ShipDataSet.PRESSURE_MIN, ShipDataSet.PRESSURE_MAX),
                 ship,
                 year,
    /* lon */   (360 * Math.random() - 180).toFixed(4),
    /* lat*/    (-90 * Math.random()).toFixed(4)
    ));
  }
}
