////////////////////////////////////////////////////////////////////////////////
//
// newshipdata.js: Add new ship data to MoNCP web application.
//
// Measurement of Net Community Production (MoNCP) of the World's Oceans:
//
// A web application that supports the viewing and analysis of data generated by
// the Nicolas Cassar Laboratory of Duke University's Nicholas School of the
// Environment.  From http://www.nicholas.duke.edu/people/faculty/cassar/: "Our
// research focuses on environmental biogeochemistry and physiology, with the
// objective of constraining the mechanisms governing carbon cycling and
// climate."
//
// Web application author:
//
// Steve Chall, Renaissance Computing Institute: stevec@renci.org
//
// Assumes that the URI that calls the associated newshipdata.html is of the
// form
//   http://<host>/<path>/newshipdata.html?startY=<startYear>
//   &startM=<startMonth>&startD=<startDay>&endY=<endYear>&endM=<endMonth>
//   &endD=<endDay>
// where the <xxx> expressions are the appropriate integers as already selected
// in moncp.html.
//
////////////////////////////////////////////////////////////////////////////////

$(document).ready(function() {
  var substring = window.location.search.split('=');
  ShipDataSet.startYear = parseInt(substring[1].match(/\d+/));
  ShipDataSet.startMonth = parseInt(substring[2].match(/\d+/));
  ShipDataSet.startDay = parseInt(substring[3].match(/\d+/));
  ShipDataSet.endYear = parseInt(substring[4].match(/\d+/));
  ShipDataSet.endMonth = parseInt(substring[5].match(/\d+/));
  ShipDataSet.endDay = parseInt(substring[6].match(/\d+/));
  
  addNSDOuterElements();
  addNewShipDataControls();
  add_ViewOrChangeShipData_controls();
  getShipDataSetsByTimeRange(ShipDataSet.startYear, ShipDataSet.startMonth,
                             ShipDataSet.startDay, ShipDataSet.endYear,
                             ShipDataSet.endMonth, ShipDataSet.endDay);

  $("#addDataButton").on("click", addNewData);
  $("#updateDataButton").on("click", updateShipDataSet);
  $("#deleteDataButton").on("click", deleteShipDataSet);
  $("#viewShipDataDropdown").on("change",
      populate_ViewOrChangeShipData_inputFields);
})


////////////////////////////////////////////////////////////////////////////////
// 
// Generate title and the three outer forms with their corresponding fieldsets
// nested inside.
//
////////////////////////////////////////////////////////////////////////////////
var addNSDOuterElements  = function() {
  $("body").append("<h3 id = 'centeredTitle'>Add/Change Ship Data (development "
      + "version #" + ShipDataSet.developmentVersion + ")</h3>");

  $("body").append("<form id = 'newShipDataForm'></form>");
  $("#newShipDataForm").append("<fieldset class = 'groupBox' "
      + "id = 'newShipDataControls'></fieldset>");

  $("body").append("<form id = 'viewShipDataForm'></form>");
  $("#viewShipDataForm").append("<fieldset class = 'groupBox' "
      + "id = 'viewShipDataControls'></fieldset>");
}

////////////////////////////////////////////////////////////////////////////////
//
////////////////////////////////////////////////////////////////////////////////
var addNewShipControls = function() {
  $("#newShipControls").append("<legend class = 'legendText'>New Ship"
      + "</legend>");
  $("#newShipControls").append("<span class = 'regFormField'>Ship Name:</span>"
      + "<input type = 'number' class = 'numEntry' id = 'shipName'><br>");
  $("#newShipControls").append("<span class = 'regFormField'>Affiliation:"
      + "</span><input type = 'number' class = 'numEntry' id = 'affiliation'>"
      + "<br>");
  $("#newShipControls").append("<span class = 'regFormField'>Researcher[s]:"
      + "</span><input type = 'number' class = 'numEntry' id = 'researchers'>"
      + "<br>");
  $("#newShipControls").append("<input type = 'button' value = 'Add Ship'"
      + "id = 'addShipButton' onclick = 'createShip'<br>");
}

////////////////////////////////////////////////////////////////////////////////
//
////////////////////////////////////////////////////////////////////////////////
var addNewShipDataControls = function() {
  $("#newShipDataControls").append("<legend class = 'legendText'>New Ship Data"
      + "</legend>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Cruise ID:"
      + "</span><input type = 'number' class = 'numEntry' id = 'cruiseID'>"
      + "<br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Year:"
      + "</span><input type = 'number' class = 'numEntry' id = 'year'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Month:"
      + "</span><input type = 'number' class = 'numEntry' id = 'month'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Day:"
      + "</span><input type = 'number' class = 'numEntry' id = 'day'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Longitude:"
      + "</span><input type = 'number' class = 'numEntry' id = 'lon'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Latitude:"
      + "</span><input type = 'number' class = 'numEntry' id = 'lat'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>O\&#8322;/Ar:"
      + "</span><input type = 'number' class = 'numEntry' id = 'o2ar'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>NCP:"
      + "</span><input type = 'number' class = 'numEntry' id = 'ncp'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Salinity:"
      + "</span><input type = 'number' class = 'numEntry' id = 'sal'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Temperature:"
      + "</span><input type = 'number' class = 'numEntry' id = 'temp'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Pressure:"
      + "</span><input type = 'number' class = 'numEntry' id = 'press'><br>");
  $("#newShipDataControls").append("<span class = 'regFormField'>Net O\&#8322;:"
      + "</span><input type = 'number' class = 'numEntry' id = 'neto2'><br>");
  $("#newShipDataControls").append("<input type = 'button' value = 'Add Data'"
      + "id = 'addDataButton' onclick = 'addNewData'<br>");
}

////////////////////////////////////////////////////////////////////////////////
//
// Instantiate a new ShipDataSet object whose variables have the values
// currently displayed in the elements in the "New Ship Data" group box, and
// append the new ShipDataSet to the "DataSet" dropdown menu in the "View or
// Change Ship Data dropdown.
//
////////////////////////////////////////////////////////////////////////////////
var addNewData = function() {
  insertShipDataSet();
  add_ViewOrChangeShipData_ShipDataSetDropdownItems();
}

////////////////////////////////////////////////////////////////////////////////
//
// Build a dropdown menu using the following input parameters:
//   parentSelector: CSS selector string that uniquely identifies parent of 
//                   dropdown to be constructed.
//   selectTitle   : the dropdown's name as seen by the user.
//   selectID      : the HTML id attribute of the dropdown to be constructed.
//   addOptions    : name of the function thst populates the dropdown.
//
////////////////////////////////////////////////////////////////////////////////
var buildDropdown = function(parentSelector, selectTitle, selectID, addOptions) {
  $(parentSelector).append("<span class = 'dropboxName'>" + selectTitle
      + ":</span>");
  $(parentSelector).append("<select id = " + selectID + "></select><br>");
  addOptions();
}

////////////////////////////////////////////////////////////////////////////////
//
// Add each Ship object in the Ship.all array to the dropdown menu in the "New
// Ship Data" group box.
//
////////////////////////////////////////////////////////////////////////////////
var add_NewShipData_ShipDropdownItems = function() {
  $("#shipDropdown").html("");

  for (var i = 0; i < Ship.all.length; i++) {
    var shipName = Ship.all[i].shipName;
    $("#shipDropdown").append($("<option>" + shipName + "</option>"));
  }
}

////////////////////////////////////////////////////////////////////////////////
//
////////////////////////////////////////////////////////////////////////////////
var add_ViewOrChangeShipData_controls = function() {
  $("#viewShipDataControls").append("<legend class = 'legendText'>"
      + "View or Change Ship Data</legend>");
  buildDropdown("#viewShipDataControls", "Data Point:", "viewShipDataDropdown",
                add_ViewOrChangeShipData_ShipDataSetDropdownItems);
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "Cruise ID:</span><input type = 'number' class = 'numEntry'"
     + "id = 'cruiseID2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "Year:</span><input type = 'number' class = 'numEntry'"
     + "id = 'year2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "Month:</span><input type = 'number' class = 'numEntry'"
     + "id = 'month2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "Day:</span><input type = 'number' class = 'numEntry'"
     + "id = 'day2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>Longitude:"
      + "</span><input type = 'number' class = 'numEntry' id = 'lon2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>Latitude:"
      + "</span><input type = 'number' class = 'numEntry' id = 'lat2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "O\&#8322;/Ar:</span><input type = 'number' class = 'numEntry' "
      + "id = 'o2ar2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField' id = 'ncpRFF'>NCP:"
      + "</span><input type = 'number' class = 'numEntry' id = 'ncp2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>Salinity:"
      + "</span><input type = 'number' class = 'numEntry' id = 'sal2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>Temperature:"
      + "</span><input type = 'number' class = 'numEntry' id = 'temp2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>Pressure:"
      + "</span><input type = 'number' class = 'numEntry' id = 'press2'><br>");
  $("#viewShipDataControls").append("<span class = 'regFormField'>"
      + "Net O\&#8322;: </span><input type = 'number' class = 'numEntry' "
      + "id = 'neto2_2'><br>");
  $("#viewShipDataControls").append("<input type = 'button' "
      + "value = 'Save Changed Values' id = 'updateDataButton'"
      + "onclick = 'updateShipDataSet'><br>");
  $("#viewShipDataControls").append("<input type = 'button' "
      + "value = 'Delete Data Point' id = 'deleteDataButton'"
      //+ "onclick = 'deleteShipDataSet' disabled = 'disabled'><br>");
      + "onclick = 'deleteShipDataSet'><br>");
  populate_ViewOrChangeShipData_inputFields();
}

////////////////////////////////////////////////////////////////////////////////
//
// Loop through the ShipDataSet.all array, adding each as an option in the
// dropdown menu with id = "viewShipDataDropdown".
//
// precondition: the ShipDataSet.all array has been built.
//
////////////////////////////////////////////////////////////////////////////////
var add_ViewOrChangeShipData_ShipDataSetDropdownItems = function() {
  $("#viewShipDataDropdown").html("");

  for (var i = 0; i < ShipDataSet.all.length; i++) {
    $("#viewShipDataDropdown").append($("<option>#"
        + ShipDataSet.all[i].id
        + "</option>"));
  }

  $("#viewShipDataDropdown")[0].selectedIndex = ShipDataSet.selectedIndex;
  
}

////////////////////////////////////////////////////////////////////////////////
//
// precondition: the Ship.all array has been built.
//
////////////////////////////////////////////////////////////////////////////////
var add_ViewOrChangeShipData_ShipDropdownItems = function() {
  getShipDataSetsByTimeRange(ShipDataSet.startYear, ShipDataSet.startMonth,
                             ShipDataSet.startDay, ShipDataSet.endYear,
                             ShipDataSet.endMonth, ShipDataSet.endDay);

  $("#changeShipDropdown").html("");

  for (var i = 0; i < Ship.all.length; i++) {
    var shipName = Ship.all[i].shipName;
    $("#changeShipDropdown").append($("<option>" + shipName + "</option>"));
  }
}

////////////////////////////////////////////////////////////////////////////////
//
// Set the elements in the "View or Change Ship Data" group box to display the
// values in the ShipDataSet object currently selected in the "DataSet" select
// element.
//
// precondition: the ShipDataSet.all array has been built.
//
////////////////////////////////////////////////////////////////////////////////
var populate_ViewOrChangeShipData_inputFields = function(e) {
  var dataSetIndex = $("#viewShipDataDropdown")[0].selectedIndex;

  if (dataSetIndex == -1) { // TEMP hack to handle opening the window
    dataSetIndex = 0;
  }

  if (typeof ShipDataSet.all[dataSetIndex] === 'undefined') {
    return;
  }

  $("#cruiseID2").val(ShipDataSet.all[dataSetIndex].ship);
  $("#year2").val(ShipDataSet.all[dataSetIndex].year);
  $("#month2").val(ShipDataSet.all[dataSetIndex].month);
  $("#day2").val(ShipDataSet.all[dataSetIndex].day);
  $("#lon2").val(ShipDataSet.all[dataSetIndex].lon);
  $("#lat2").val(ShipDataSet.all[dataSetIndex].lat);
  $("#o2ar2").val(ShipDataSet.all[dataSetIndex].o2ar);
  $("#ncp2").val(ShipDataSet.all[dataSetIndex].ncp);
  $("#ncp2").val(ShipDataSet.all[dataSetIndex].ncp);
  $("#sal2").val(ShipDataSet.all[dataSetIndex].salinity);
  $("#temp2").val(ShipDataSet.all[dataSetIndex].temperature);
  $("#press2").val(ShipDataSet.all[dataSetIndex].pressure);
  $("#neto2_2").val(ShipDataSet.all[dataSetIndex].neto2);
}
