////////////////////////////////////////////////////////////////////////////////
//
// register.js: sign up as an MoNCP user.
// 
// Measurement of Net Community Production (MoNCP) of the World's Oceans:
// 
// A web application that supports the viewing and analysis of data generated by
// the Nicolas Cassar Laboratory of Duke University's Nicholas School of the
// Environment.  From http://www.nicholas.duke.edu/people/faculty/cassar/: "Our
// research focuses on environmental biogeochemistry and physiology, with the
// objective of constraining the mechanisms governing carbon cycling and
// climate."
// 
// Web application authors:
// 
// Steve Chall, Renaissance Computing Institute:  stevec@renci.org
// Matt Pittman, University of North Carolina at Chapel Hill: mattpitt@unc.edu
// 
////////////////////////////////////////////////////////////////////////////////

$(document).ready(function() {
  populateForm();
})

////////////////////////////////////////////////////////////////////////////////
//
////////////////////////////////////////////////////////////////////////////////
var populateForm = function() {
  $("body").append("<h2 id = 'centeredTitle'>MoNCP Registration</h2>");

  $("body").append("<form id = 'mainForm'>");
  $("#mainForm").append("<fieldset class = 'groupBox' id = 'topBox'>");
  $("#topBox").append("<legend class = 'legendText' id = 'registerTitle'>"
	  + "Create a New Account</legend><br>");	  
  $("#topBox").append("<fieldset class = 'groupBox' id = 'userInfo'>");
  $("#userInfo").append("<legend class = 'legendText'>User Information"
	  + "</legend>");
  $("#userInfo").append("<span class = 'regFormField'>Email Address:</span>"
	  + "<input type = 'text' id = 'email' class = 'textEntry'/><br>");
  $("#userInfo").append("<span class = 'regFormField'>User name <span class ="
	  + "'warningSub'>(6-14 characters)</span>:</span> <input type = 'text'" 
	  + "id = 'userName' class = 'textEntry'/><br>");
  $("#userInfo").append("<span class = 'regFormField'>Password <span class = "
	  + "'warningSub'>(8-16 characters)</span>:</span> <input type = "
	  + "'password' id = 'password' class = 'textEntry'/><br>");
  $("#userInfo").append("<span class = 'regFormField'>Re-enter Password:"
	  + "</span> <input type = 'password' id = 'repassword' class = 'textEntry'/>");
  $("#userInfo").append("</fieldset><br>");

  $("#topBox").append("<br><fieldset class = 'groupBox' id = 'personalInfo'>");
  $("#personalInfo").append("<legend class = 'legendText'>Personal Information"
	  + "</legend>");
  $("#personalInfo").append("<span class = 'regFormField'>First Name:</span>"
	  + "<input type = 'text' id = 'firstName' class = 'textEntry'><br>");
  $("#personalInfo").append("<span class = 'regFormField'>Last Name:</span>"
	  + "<input type = 'text' id = 'lastName' class = 'textEntry'><br>");
  $("#personalInfo").append("<span class = 'regFormField'>Affiliation:"
	  + "</span>");
  $("#personalInfo").append("<select id = 'selectBox'>");
  $("#selectBox").append("<option>None</option>");
  $("#selectBox").append("<option>Duke University</option>");
  $("#selectBox").append("<option>RENCI</option>");
  $("#selectBox").append("<option>University of California-Santa Barbara</option>");
  $("#selectBox").append("<option>University of North Carolina-Chapel Hill</option>");
  $("#selectBox").append("<option>Add New Affiliation...</option>");
  $("#personalInfo").append("</select>");
  $("#personalInfo").append("</fieldset>");
  
  $("#topBox").append("<br><input type = 'button' value = 'Create Account'"
	  + "class = 'centeredElt' + onClick = 'createUser()'><br>");
  $("#topBox").append("</fieldset>");
  $("mainForm").append("</form>");
}

////////////////////////////////////////////////////////////////////////////////
//	Note: stub
////////////////////////////////////////////////////////////////////////////////
var createUser = function() {
	var userName = $("#userName").val();
	if(userName.length > 14 || userName.length < 6){
		alert("User name does not meet requirements!");
	}
	var firstName = $("#firstName").val();
	var lastName = $("#lastName").val();
	var affiliation = $("#selectBox").val();
	var email = $("#email").val();
	//NOTE: Passwords should NEVER be stored in variables, this is just placeholder code!
	var password = $("#password").val();
	var repassword = $("#repassword").val();
	if(password.length > 16 || password.length < 8){
		alert("Password does not meet requirements!");
	}
	if(password != repassword){
		alert("Passwords do not match!");
	}
	var newUser = new User(firstName, lastName, affiliation, email, userName, password);
	newUser.outputUser();
}