////////////////////////////////////////////////////////////////////////////////
// vis.js: stub for visualization tools webpage
//
// Measurement of Net Community Production (MoNCP) of the World's Oceans:
//
// A web application that supports the viewing and analysis of data generated by
// the Nicolas Cassar Laboratory of Duke University's Nicholas School of the
// Environment.  From http://www.nicholas.duke.edu/people/faculty/cassar/: "Our
// research focuses on environmental biogeochemistry and physiology, with the
// objective of constraining the mechanisms governing carbon cycling and
// climate."
//
// Web application author:
//
// Steve Chall, Renaissance Computing Institute: stevec@renci.org
//
////////////////////////////////////////////////////////////////////////////////

$(document).ready(function() {
  $("body").append("<h3 id = 'centeredTitle'>Visualization tools: " + 
      "under construction</h3>");
  $("body").append("<form id = 'visOuterForm'></form>");
  $("#visOuterForm").append("<fieldset class = 'groupBox' "
      + "id = 'visFieldset'></fieldset>");
  $("#visFieldset").append("<img class = 'centeredElt' id = '3dvis' "
      + "src = 'graph3d.png' alt = '3D Cartesian graph visualization' "
      + "title = 'Visualization tools coming'>");
})

